### ISSUE TITLE
Rich text widget displays: 'Did you mean .raw or .output?'

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.textfield#22]
- Create a dexterity content type through the web and give it a rich text field.
- Create an instance of it with some text.
- View it and you do not see your text, but only 'RichTextValue object. (Did you mean .raw or .output?)', which is what the `__repr__` of the textfield returns.

See https://community.plone.org/t/dexterity-richtext-content-is-not-showing-after-upgrade/4475
I checked it on Plone 4.3, and is reported as also being a problem on 5.0 and 5.1.

Switching plone.app.textfield back from 1.2.8 to 1.2.7 fixes it, so this was introduced with the merge of @jensens pull request #20. 
(It seems Jens intended this to be released as 1.3.0 as it is a new feature, but the version number in `setup.py` was not changed and it ended up being released as 1.2.8.)

@jensens Can you see how this should be fixed?

**Comment by mauritsvanrees** [comment]
I actually only see this in 4.3, not in 5.0 or 5.1. I have made a pull request.

**Comment by tkimnguyen** [comment]
Ha! All this time I've been wondering how to fix this... thx!!!
