### ISSUE TITLE
plone.app.textfield.RichText should have allow_file_upload=bool option

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.app.textfield#4]
_Original author: msmit...@zimbra.naz.edu (September 08, 2010 18:34:50)_

atapi.RichWidget has an option called allow_file_upload, which is True by default, but if False hides the Image button and doesn't allow the user to upload reference objects. This behavior has been useful in AT, and I believe it would be useful in Dexterity as well.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=138_

**Comment by jensens** [comment]
outdated
