### ISSUE TITLE
Relative links are interpreted relative to Site Root, not the content object

### ISSUE THREAD

**Issue by reinhardt** [plone/plone.app.textfield#7]
If my site has the id Plone and contains the page /Plone/en/materials/materials, who's text field contains the link

```<a href="../partners">...</a>```

then the rendered page links to localhost:8080/partners. What I would expect (and what Archtypes does) is the link to point to localhost:8080/Plone/en/partners.

The reason is that RichTextValue.output() uses the site as the context for calling portal_transforms. What it should do is use the content object.

See https://github.com/plone/plone.app.textfield/blob/master/plone/app/textfield/value.py#L70

**Comment by thet** [comment]
Yes, you have to call the output method of the TextValue and pass the current context to it - as the TextValue cannot access the context itself.
Like: ``<p tal:content="structure python:context.text.output_relative_to(view.context)"/>`` ( https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/browser/templates/document.pt )

**Comment by reinhardt** [comment]
Thanks!
